using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using GeckoUBL.Ubl21.Cbc;
using GeckoUBL.Ubl21.Ccts;
using GeckoUBL.Ubl21.Cec;
using ValueType = System.ValueType;

namespace GeckoUBL.Ubl21.Udt
{
	/// <remarks/>
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ReferencedSignatureIDType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ExtensionVersionIDType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ExtensionURIType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ExtensionAgencyURIType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ExtensionAgencyIDType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(WebsiteURIType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(VesselIDType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(VersionIDType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(VariantIDType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ValidatorIDType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(UpperOrangeHazardPlacardIDType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(UUIDType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(URIType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(UBLVersionIDType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(TransportationServiceDetailsURIType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(TransportExecutionPlanReferenceIDType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(TrainIDType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(TrackingIDType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(TraceIDType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(TenderEnvelopeIDType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(SupplierAssignedAccountIDType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(SuccessiveSequenceIDType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(SubscriberIDType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(SpecificationIDType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(SignatureIDType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ShippingOrderIDType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(SerialIDType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(SequenceNumberIDType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(SequenceIDType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(SellerEventIDType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(SecurityIDType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(SchemeURIType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(SalesOrderLineIDType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(SalesOrderIDType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(RevisedForecastLineIDType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(RequiredCustomsIDType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(RequestForQuotationLineIDType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ReleaseIDType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(RegistrationNationalityIDType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(RegistrationIDType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ReferencedConsignmentIDType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ReferenceIDType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(RailCarIDType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(RadioCallSignIDType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ProfileIDType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ProfileExecutionIDType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ProductTraceIDType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(PrimaryAccountNumberIDType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(PreviousVersionIDType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(PreviousJobIDType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(PrepaidPaymentReferenceIDType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(PerformingCarrierAssignedIDType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(PaymentTermsDetailsURIType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(PaymentMeansIDType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(PaymentIDType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ParentDocumentVersionIDType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ParentDocumentLineReferenceIDType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ParentDocumentIDType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(OriginalJobIDType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(OriginalContractingSystemIDType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(OpenTenderIDType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(OntologyURIType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(NetworkIDType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(NationalityIDType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(MarkingIDType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(LowerOrangeHazardPlacardIDType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(LotNumberIDType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(LogoReferenceIDType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(LocationIDType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(LoadingSequenceIDType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(LineIDType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(LicensePlateIDType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(LanguageIDType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(JourneyIDType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(IssuerIDType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(IssueNumberIDType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(InstructionIDType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(InformationURIType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ImmobilizationCertificateIDType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(IdentificationIDType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(IDType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(HazardClassIDType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(FreightForwarderAssignedIDType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ExtendedIDType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ExchangeMarketIDType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(EndpointIDType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(EconomicOperatorRegistryURIType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(DocumentIDType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(CustomizationIDType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(CustomerAssignedAccountIDType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ContractedCarrierAssignedIDType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ContractFolderIDType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ConsumptionReportIDType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ConsumptionIDType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ConsignorAssignedIDType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ConsigneeAssignedIDType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(CompanyIDType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ChipApplicationIDType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(CarrierAssignedIDType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(CV2IDType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(BuyerProfileURIType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(BuyerEventIDType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(BusinessIdentityEvidenceIDType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(BusinessClassificationEvidenceIDType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(BrokerAssignedIDType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(BarcodeSymbologyIDType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(AwardingCriterionIDType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(AuctionURIType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(AttributeIDType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(AircraftIDType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(AgencyIDType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(AdditionalAccountIDType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(AccountIDType))]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(TypeName = "IdentifierType", Namespace = "urn:oasis:names:specification:ubl:schema:xsd:UnqualifiedDataTypes-2")]
	public partial class IdentifierType1 : IdentifierType
	{
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:oasis:names:specification:ubl:schema:xsd:UnqualifiedDataTypes-2")]
	public partial class VideoType : BinaryObjectType
	{
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:oasis:names:specification:ubl:schema:xsd:UnqualifiedDataTypes-2")]
	public partial class SoundType : BinaryObjectType
	{
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:oasis:names:specification:ubl:schema:xsd:UnqualifiedDataTypes-2")]
	public partial class PictureType : BinaryObjectType
	{
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:oasis:names:specification:ubl:schema:xsd:UnqualifiedDataTypes-2")]
	public partial class GraphicType : BinaryObjectType
	{
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(EmbeddedDocumentBinaryObjectType))]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(TypeName = "BinaryObjectType", Namespace = "urn:oasis:names:specification:ubl:schema:xsd:UnqualifiedDataTypes-2")]
	public partial class BinaryObjectType1 : BinaryObjectType
	{
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(TargetCurrencyBaseRateType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(SourceCurrencyBaseRateType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(RateType1))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(OrderableUnitFactorRateType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(CalculationRateType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(AmountRateType))]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:oasis:names:specification:ubl:schema:xsd:UnqualifiedDataTypes-2")]
	public partial class RateType : NumericType
	{
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(TierRatePercentType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(TargetServicePercentType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(SettlementDiscountPercentType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ReliabilityPercentType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ProgressPercentType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(PercentType1))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(PenaltySurchargePercentType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(PaymentPercentType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ParticipationPercentType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(PartecipationPercentType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(MinimumPercentType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(MaximumPercentType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(HumidityPercentType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(AirFlowPercentType))]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:oasis:names:specification:ubl:schema:xsd:UnqualifiedDataTypes-2")]
	public partial class PercentType : NumericType
	{
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(TypeName = "ValueType", Namespace = "urn:oasis:names:specification:ubl:schema:xsd:UnqualifiedDataTypes-2")]
	public partial class ValueType1 : NumericType
	{
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(WeightNumericType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(SequenceNumericType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ResidentOccupantsNumericType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ReminderSequenceNumericType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(PackSizeNumericType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(OrderQuantityIncrementNumericType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(OrderIntervalDaysNumericType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(MultiplierFactorNumericType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(MinimumNumberNumericType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(MaximumPaymentInstructionsNumericType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(MaximumNumberNumericType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(MaximumCopiesNumericType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(LineNumberNumericType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(LineCountNumericType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(FrozenPeriodDaysNumericType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(CalculationSequenceNumericType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(BudgetYearNumericType))]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(TypeName = "NumericType", Namespace = "urn:oasis:names:specification:ubl:schema:xsd:UnqualifiedDataTypes-2")]
	public partial class NumericType1 : NumericType
	{
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ValueAmountType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(TransactionCurrencyTaxAmountType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(TotalTaxAmountType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(TotalTaskAmountType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(TotalPaymentAmountType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(TotalInvoiceAmountType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(TotalDebitAmountType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(TotalCreditAmountType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(TotalBalanceAmountType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(TotalAmountType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ThresholdAmountType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(TaxableAmountType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(TaxInclusiveAmountType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(TaxExclusiveAmountType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(TaxEnergyOnAccountAmountType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(TaxEnergyBalanceAmountType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(TaxEnergyAmountType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(TaxAmountType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(SettlementDiscountAmountType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(RoundingAmountType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(RequiredFeeAmountType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(PriceAmountType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(PrepaidAmountType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(PerUnitAmountType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(PenaltyAmountType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(PayableRoundingAmountType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(PayableAmountType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(PayableAlternativeAmountType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(PartyCapacityAmountType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(PaidAmountType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(MinimumAmountType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(MaximumPaidAmountType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(MaximumAmountType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(MaximumAdvertisementAmountType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(MarketValueAmountType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(LowerTenderAmountType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(LineExtensionAmountType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(LiabilityAmountType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(InventoryValueAmountType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(InsuranceValueAmountType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(InsurancePremiumAmountType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(HigherTenderAmountType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(FreeOnBoardValueAmountType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(FeeAmountType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(FaceValueAmountType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(EstimatedOverallContractAmountType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(EstimatedAmountType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(DocumentationFeeAmountType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(DeclaredStatisticsValueAmountType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(DeclaredForCarriageValueAmountType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(DeclaredCustomsValueAmountType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(DeclaredCarriageValueAmountType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(DebitLineAmountType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(CreditLineAmountType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(CorrectionUnitAmountType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(CorrectionAmountType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(CorporateStockAmountType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ChargeTotalAmountType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(CallExtensionAmountType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(CallBaseAmountType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(BaseAmountType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(BalanceAmountType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(AverageSubsequentContractAmountType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(AverageAmountType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(AnnualAverageAmountType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(AmountType2))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(AllowanceTotalAmountType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(AdvertisementAmountType))]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(TypeName = "AmountType", Namespace = "urn:oasis:names:specification:ubl:schema:xsd:UnqualifiedDataTypes-2")]
	public partial class AmountType1 : AmountType
	{
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(VarianceQuantityType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ValueQuantityType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(TotalTransportHandlingUnitQuantityType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(TotalPackagesQuantityType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(TotalPackageQuantityType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(TotalMeteredQuantityType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(TotalGoodsItemQuantityType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(TotalDeliveredQuantityType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(TotalConsumedQuantityType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(TimeDeltaDaysQuantityType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ThresholdQuantityType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(TargetInventoryQuantityType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ShortQuantityType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(SharesNumberQuantityType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ReturnableQuantityType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(RejectedQuantityType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ReceivedTenderQuantityType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ReceivedQuantityType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ReceivedForeignTenderQuantityType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ReceivedElectronicTenderQuantityType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(QuantityType2))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(PreviousMeterQuantityType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(PerformanceValueQuantityType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(PassengerQuantityType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(PackQuantityType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(OversupplyQuantityType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(OutstandingQuantityType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(OperatingYearsQuantityType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(NormalTemperatureReductionQuantityType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(MultipleOrderQuantityType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(MinimumQuantityType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(MinimumOrderQuantityType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(MinimumInventoryQuantityType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(MinimumBackorderQuantityType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(MaximumVariantQuantityType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(MaximumQuantityType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(MaximumOrderQuantityType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(MaximumOperatorQuantityType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(MaximumBackorderQuantityType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(LatestMeterQuantityType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(InvoicedQuantityType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(GasPressureQuantityType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ExpectedQuantityType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ExpectedOperatorQuantityType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(EstimatedOverallContractQuantityType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(EstimatedConsumedQuantityType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(EmployeeQuantityType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(DifferenceTemperatureReductionQuantityType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(DeliveredQuantityType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(DebitedQuantityType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(CustomsTariffQuantityType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(CrewQuantityType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(CreditedQuantityType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ContentUnitQuantityType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ConsumptionWaterQuantityType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ConsumptionEnergyQuantityType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ConsumerUnitQuantityType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ConsignmentQuantityType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ChildConsignmentQuantityType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ChargeableQuantityType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(BatchQuantityType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(BasicConsumedQuantityType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(BaseQuantityType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(BackorderQuantityType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ActualTemperatureReductionQuantityType))]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(TypeName = "QuantityType", Namespace = "urn:oasis:names:specification:ubl:schema:xsd:UnqualifiedDataTypes-2")]
	public partial class QuantityType1 : QuantityType
	{
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ValueMeasureType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(TareWeightMeasureType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(SourceValueMeasureType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(PreEventNotificationDurationMeasureType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(PostEventNotificationDurationMeasureType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(NetWeightMeasureType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(NetVolumeMeasureType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(NetTonnageMeasureType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(NetNetWeightMeasureType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(MinimumMeasureType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(MeasureType2))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(MaximumMeasureType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(LongitudeMinutesMeasureType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(LongitudeDegreesMeasureType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(LoadingLengthMeasureType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(LeadTimeMeasureType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(LatitudeMinutesMeasureType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(LatitudeDegreesMeasureType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(GrossWeightMeasureType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(GrossVolumeMeasureType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(GrossTonnageMeasureType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(DurationMeasureType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ComparedValueMeasureType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ChargeableWeightMeasureType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(BaseUnitMeasureType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(AltitudeMeasureType))]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(TypeName = "MeasureType", Namespace = "urn:oasis:names:specification:ubl:schema:xsd:UnqualifiedDataTypes-2")]
	public partial class MeasureType1 : MeasureType
	{
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(VariantConstraintIndicatorType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(UnknownPriceIndicatorType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ToOrderIndicatorType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ThirdPartyPayerIndicatorType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(TaxIncludedIndicatorType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(TaxEvidenceIndicatorType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(StatusAvailableIndicatorType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(SplitConsignmentIndicatorType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(SpecialSecurityIndicatorType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(SoleProprietorshipIndicatorType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ReturnableMaterialIndicatorType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ReturnabilityIndicatorType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(RequiredCurriculaIndicatorType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(RefrigerationOnIndicatorType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(RefrigeratedIndicatorType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(PublishAwardIndicatorType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(PrizeIndicatorType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(PricingUpdateRequestIndicatorType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(PrepaidIndicatorType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(PreCarriageIndicatorType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(PowerIndicatorType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(PartialDeliveryIndicatorType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(OtherConditionsIndicatorType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(OrderableIndicatorType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(OptionalLineItemIndicatorType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(OnCarriageIndicatorType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(MarkCareIndicatorType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(MarkAttentionIndicatorType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(LivestockIndicatorType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(LegalStatusIndicatorType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ItemUpdateRequestIndicatorType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(IndicationIndicatorType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(HumanFoodIndicatorType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(HumanFoodApprovedIndicatorType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(HazardousRiskIndicatorType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(GovernmentAgreementConstraintIndicatorType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(GeneralCargoIndicatorType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(FullyPaidSharesIndicatorType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(FrozenDocumentIndicatorType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(FreeOfChargeIndicatorType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(FollowupContractIndicatorType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(DangerousGoodsApprovedIndicatorType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(CustomsImportClassifiedIndicatorType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(CopyIndicatorType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ContainerizedIndicatorType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ConsolidatableIndicatorType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(CompletionIndicatorType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ChargeIndicatorType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(CatalogueIndicatorType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(CandidateReductionConstraintIndicatorType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(BulkCargoIndicatorType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(BindingOnBuyerIndicatorType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(BasedOnConsensusIndicatorType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(BalanceBroughtForwardIndicatorType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(BackOrderAllowedIndicatorType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(AuctionConstraintIndicatorType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(AnimalFoodIndicatorType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(AnimalFoodApprovedIndicatorType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(AdValoremIndicatorType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(AcceptedIndicatorType))]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:oasis:names:specification:ubl:schema:xsd:UnqualifiedDataTypes-2")]
	public partial class IndicatorType
	{

		private bool valueField;

		/// <remarks/>
		[System.Xml.Serialization.XmlTextAttribute()]
		public bool Value
		{
			get
			{
				return this.valueField;
			}
			set
			{
				this.valueField = value;
			}
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(VesselNameType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(TechnicalNameType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(StreetNameType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ServiceNameType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(RoamingPartnerNameType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(RetailEventNameType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(RegistrationNameType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(OtherNameType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(NameType1))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ModelNameType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(MiddleNameType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(HolderNameType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(FirstNameType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(FileNameType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(FamilyNameType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(CitySubdivisionNameType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(CityNameType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(CategoryNameType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(BuildingNameType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(BrandNameType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(BlockNameType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(AliasNameType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(AdditionalStreetNameType))]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:oasis:names:specification:ubl:schema:xsd:UnqualifiedDataTypes-2")]
	public partial class NameType : TextType
	{
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ExtensionReasonType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ExtensionAgencyNameType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(XPathType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(WorkPhaseType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(WeightType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(WarrantyInformationType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ValueType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ValueQualifierType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ValidateToolVersionType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ValidateToolType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ValidateProcessType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(TransportationServiceDescriptionType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(TransportUserSpecialTermsType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(TransportUserRemarksType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(TransportServiceProviderSpecialTermsType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(TransportServiceProviderRemarksType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(TradingRestrictionsType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(TitleType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(TimingComplaintType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(TimezoneOffsetType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(TimeAmountType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(TierRangeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(TextType2))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(TestMethodType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(TelephoneType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(TelefaxType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(TelecommunicationsSupplyTypeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(TelecommunicationsServiceCategoryType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(TelecommunicationsServiceCallType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(TechnicalCommitteeDescriptionType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(TaxExemptionReasonType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(TariffDescriptionType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(SummaryDescriptionType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(SubscriberTypeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(StatusReasonType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(SpecialTransportRequirementsType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(SpecialTermsType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(SpecialServiceInstructionsType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(SpecialInstructionsType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(SignatureMethodType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ShipsRequirementsType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ShippingMarksType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ServiceTypeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ServiceNumberCalledType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(SealingPartyTypeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(RoomType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(RoleDescriptionType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ResolutionType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ResidenceTypeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ReplenishmentOwnerDescriptionType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(RemarksType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(RejectionNoteType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(RejectReasonType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(RegulatoryDomainType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(RegistrationNationalityType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(RegionType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ReferenceType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(RankType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(PurposeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ProcessReasonType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ProcessDescriptionType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(PrizeDescriptionType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(PriorityType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(PrintQualifierType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(PriceTypeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(PriceRevisionFormulaDescriptionType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(PriceChangeReasonType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(PreviousMeterReadingMethodType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(PostboxType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(PostalZoneType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(PlotIdentificationType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(PlacardNotationType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(PlacardEndorsementType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(PhoneNumberType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(PersonalSituationType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(PaymentOrderReferenceType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(PaymentNoteType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(PaymentDescriptionType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(PayerReferenceType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(PayPerViewType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(PasswordType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(PartyTypeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(PackingMaterialType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(OutstandingReasonType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(OtherInstructionType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(OrganizationDepartmentType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(OrderableUnitType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(OptionsDescriptionType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(OneTimeChargeTypeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(NoteType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(NegotiationDescriptionType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(NameSuffixType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(MovieTitleType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(MonetaryScopeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(MinimumValueType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(MinimumImprovementBidType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(MeterReadingTypeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(MeterReadingCommentsType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(MeterNumberType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(MeterNameType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(MeterConstantType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(MaximumValueType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(MarkCareType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(MarkAttentionType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(LowTendersDescriptionType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(LossRiskType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(LoginType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(LocationType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ListValueType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(LineType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(LimitationDescriptionType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(LegalReferenceType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(LatestMeterReadingMethodType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(KeywordType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(JustificationType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(JustificationDescriptionType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(JobTitleType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(InvoicingPartyReferenceType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(InstructionsType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(InstructionNoteType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(InhouseMailType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(InformationType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(HeatingTypeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(HaulageInstructionsType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(HashAlgorithmMethodType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(HandlingInstructionsType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(FundingProgramType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(FrequencyType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ForwarderServiceInstructionsType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(FloorType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(FeeDescriptionType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ExtensionType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ExpressionType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ExemptionReasonType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ExclusionReasonType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ElectronicMailType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ElectronicDeviceDescriptionType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(DutyType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(DocumentTypeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(DocumentStatusReasonDescriptionType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(DocumentHashType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(DocumentDescriptionType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(DistrictType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(DescriptionType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(DepartmentType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(DemurrageInstructionsType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(DeliveryInstructionsType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(DataSendingCapabilityType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(DamageRemarksType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(CustomsClearanceServiceInstructionsType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(CustomerReferenceType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(CurrentChargeTypeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(CountrySubentityType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(CorrectionTypeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ContractTypeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ContractSubdivisionType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ContractNameType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ContentType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ConsumptionTypeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ConsumptionLevelType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ConsumersEnergyLevelType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ConditionsType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ConditionsDescriptionType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ConditionType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(CompanyLegalFormType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(CommentType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(CodeValueType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(CharacteristicsType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ChannelType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ChangeConditionsType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(CertificateTypeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(CarrierServiceInstructionsType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(CanonicalizationMethodType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(CandidateStatementType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(CancellationNoteType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(CalculationExpressionType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(BuyerReferenceType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(BuildingNumberType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(BirthplaceNameType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(BackorderReasonType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(AwardingCriterionDescriptionType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ApprovalStatusType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(AllowanceChargeReasonType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(AgencyNameType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(AdditionalInformationType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(AdditionalConditionsType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ActivityTypeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(AccountingCostType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(AcceptedVariantsDescriptionType))]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(TypeName = "TextType", Namespace = "urn:oasis:names:specification:ubl:schema:xsd:UnqualifiedDataTypes-2")]
	public partial class TextType1 : TextType
	{
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ExtensionReasonCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(WorkPhaseCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(WeightingAlgorithmCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(WeekDayCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ValidationResultCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(UtilityStatementTypeCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(UrgencyCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(UNDGCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(TypeCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(TransportationStatusTypeCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(TransportServiceCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(TransportModeCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(TransportMeansTypeCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(TransportHandlingUnitTypeCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(TransportExecutionStatusCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(TransportEventTypeCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(TransportEquipmentTypeCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(TransportEmergencyCardCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(TransportAuthorizationCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(TransitDirectionCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(TradeServiceCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(TradeItemPackingLabelingTypeCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(TrackingDeviceCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(TimingComplaintCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(TimeFrequencyCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ThresholdValueComparisonCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(TendererRoleCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(TendererRequirementTypeCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(TenderTypeCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(TenderResultCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(TenderEnvelopeTypeCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(TelecommunicationsSupplyTypeCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(TelecommunicationsServiceCategoryCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(TelecommunicationsServiceCallCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(TaxTypeCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(TaxLevelCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(TaxExemptionReasonCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(TaxCurrencyCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(TariffCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(TariffClassCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(TargetCurrencyCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(SupplyChainActivityTypeCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(SubstitutionStatusCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(SubscriberTypeCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(SubmissionMethodCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(SubcontractingConditionsCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(StatusReasonCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(StatusCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(StatementTypeCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(SpecificationTypeCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(SourceCurrencyCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(SizeTypeCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ShortageActionCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ShippingPriorityLevelCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ServiceTypeCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ServiceInformationPreferenceCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(SecurityClassificationCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(SealStatusCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(SealIssuerTypeCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(RoleCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(RevisionStatusCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(RetailEventStatusCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ResponseCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ResolutionCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ResidenceTypeCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(RequestedInvoiceCurrencyCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ReminderTypeCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(RejectReasonCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(RejectActionCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ReferenceEventCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ReceiptAdviceTypeCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(QuantityDiscrepancyCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(QualityControlCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(PurposeCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ProviderTypeCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(PromotionalEventTypeCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ProfileStatusCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ProcurementTypeCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ProcurementSubTypeCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ProcessReasonCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ProcedureCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(PrivacyCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(PricingCurrencyCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(PriceTypeCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(PriceEvaluationCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(PreviousMeterReadingMethodCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(PreviousCancellationReasonCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(PreferenceCriterionCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(PositionCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(PerformanceMetricTypeCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(PaymentPurposeCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(PaymentMeansCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(PaymentFrequencyCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(PaymentCurrencyCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(PaymentChannelCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(PaymentAlternativeCurrencyCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(PartyTypeCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(PartPresentationCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ParentDocumentTypeCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(PackingCriteriaCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(PackagingTypeCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(PackageLevelCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(PackLevelCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(OwnerTypeCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(OrderTypeCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(OrderResponseCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(OneTimeChargeTypeCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(NotificationTypeCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(NatureCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(NameCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(MiscellaneousEventTypeCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(MimeCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(MeterReadingTypeCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(MeterConstantCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(MedicalFirstAidGuideCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(MathematicOperatorCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(MandateTypeCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(LossRiskResponsibilityCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(LongitudeDirectionCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(LocationTypeCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(LocaleCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(LineStatusCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(LifeCycleStatusCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(LatitudeDirectionCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(LatestMeterReadingMethodCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ItemClassificationCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(InvoiceTypeCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(InspectionMethodCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(InhalationToxicityZoneCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(IndustryClassificationCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ImportanceCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(IdentificationCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(HeatingTypeCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(HazardousRegulationCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(HazardousCategoryCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(HandlingCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(GuaranteeTypeCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(GenderCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(FundingProgramCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(FullnessIndicationCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(FreightRateClassCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(FormatCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ForecastTypeCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ForecastPurposeCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(FinancingInstrumentCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(FeatureTacticTypeCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ExpressionCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ExpenseCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ExemptionReasonCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ExecutionRequirementCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ExceptionStatusCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ExceptionResolutionCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(EvidenceTypeCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(EvaluationCriterionTypeCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(EnvironmentalEmissionTypeCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(EncodingCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(EmergencyProceduresCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(DutyCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(DocumentTypeCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(DocumentStatusReasonCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(DocumentStatusCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(DocumentCurrencyCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(DispositionCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(DisplayTacticTypeCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(DirectionCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(DespatchAdviceTypeCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(DescriptionCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(DeclarationTypeCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(DataSourceCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(CustomsStatusCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(CurrentChargeTypeCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(CurrencyCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(CreditNoteTypeCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(CountrySubentityCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(CorrectionTypeCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(CorporateRegistrationTypeCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(CoordinateSystemCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ContractingSystemCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ContractTypeCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ConsumptionTypeCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ConsumptionLevelCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ConsumersEnergyLevelCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ConsumerIncentiveTacticTypeCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ConstitutionCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ConditionCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ComparisonDataSourceCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ComparisonDataCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(CompanyLiquidationStatusCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(CompanyLegalFormCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(CommodityCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(CollaborationPriorityCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(CharacterSetCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ChannelCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(CertificateTypeCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(CargoTypeCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(CardTypeCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(CardChipCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(CapabilityTypeCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(CalculationMethodCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(CalculationExpressionCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(AwardingMethodTypeCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(AwardingCriterionTypeCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(AvailabilityStatusCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ApplicationStatusCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(AllowanceChargeReasonCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(AdmissionCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(AdjustmentReasonCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(AddressTypeCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(AddressFormatCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ActivityTypeCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ActionCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(AccountingCostCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(AccountTypeCodeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(AccountFormatCodeType))]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(TypeName = "CodeType", Namespace = "urn:oasis:names:specification:ubl:schema:xsd:UnqualifiedDataTypes-2")]
	public partial class CodeType1 : CodeType
	{
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ValidationTimeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(StartTimeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(SourceForecastIssueTimeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(RevisionTimeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ResponseTimeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ResolutionTimeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(RequiredDeliveryTimeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(RequestedDespatchTimeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(RegisteredTimeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ReferenceTimeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(PaidTimeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(OccurrenceTimeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(NominationTimeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ManufactureTimeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(LatestPickupTimeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(LatestDeliveryTimeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(LastRevisionTimeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(IssueTimeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(GuaranteedDespatchTimeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ExpiryTimeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(EstimatedDespatchTimeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(EstimatedDeliveryTimeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(EndTimeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(EffectiveTimeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(EarliestPickupTimeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ComparisonForecastIssueTimeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(CallTimeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(AwardTimeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ActualPickupTimeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ActualDespatchTimeType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ActualDeliveryTimeType))]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:oasis:names:specification:ubl:schema:xsd:UnqualifiedDataTypes-2")]
	public partial class TimeType
	{

		private System.DateTime valueField;

		/// <remarks/>
		[System.Xml.Serialization.XmlTextAttribute(DataType = "time")]
		public System.DateTime Value
		{
			get
			{
				return this.valueField;
			}
			set
			{
				this.valueField = value;
			}
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ValidityStartDateType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ValidationDateType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(TaxPointDateType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(SubmissionDueDateType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(SubmissionDateType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(StartDateType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(SourceForecastIssueDateType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(RevisionDateType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ResponseDateType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ResolutionDateType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(RequiredDeliveryDateType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(RequestedPublicationDateType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(RequestedDespatchDateType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(RequestedDeliveryDateType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(RegistrationExpirationDateType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(RegistrationDateType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(RegisteredDateType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ReferenceDateType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ReceivedDateType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(PreviousMeterReadingDateType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(PlannedDateType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(PaymentDueDateType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(PaidDateType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(OccurrenceDateType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(NominationDateType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ManufactureDateType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(LatestSecurityClearanceDateType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(LatestProposalAcceptanceDateType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(LatestPickupDateType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(LatestMeterReadingDateType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(LatestDeliveryDateType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(LastRevisionDateType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(IssueDateType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(InstallmentDueDateType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(GuaranteedDespatchDateType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(FirstShipmentAvailibilityDateType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ExpiryDateType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(EstimatedDespatchDateType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(EstimatedDeliveryDateType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(EndDateType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(EffectiveDateType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(EarliestPickupDateType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(DueDateType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(DateType1))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ComparisonForecastIssueDateType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(CallDateType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(BirthDateType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(BestBeforeDateType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(AwardDateType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(AvailabilityDateType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ApprovalDateType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ActualPickupDateType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ActualDespatchDateType))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ActualDeliveryDateType))]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:oasis:names:specification:ubl:schema:xsd:UnqualifiedDataTypes-2")]
	public partial class DateType
	{

		private System.DateTime valueField;

		/// <remarks/>
		[System.Xml.Serialization.XmlTextAttribute(DataType = "date")]
		public System.DateTime Value
		{
			get
			{
				return this.valueField;
			}
			set
			{
				this.valueField = value;
			}
		}
	}

}
